/*
Locatr simplifies the process of generating HTML element locators from your straightforward descriptions. It currently supports Playwright and will soon offer compatibility with Selenium and other frameworks. With its internal caching system, Locatr enhances efficiency in locator generation, making your web automation tasks smoother.

Example:

	starButtonLocator, err := locatr.GetLocatr("Star button on the page")
	starButtonLocator.click()

To get started, let's open a new page in the browser using playwright-go.

	func main() {
		pw, _ := playwright.Run()
		defer pw.Stop()
		browser, _ := pw.Chromium.Launch(
			playwright.BrowserTypeLaunchOptions{
				Headless: playwright.Bool(false),
			},
		)
		defer browser.Close()
		page, _ := browser.NewPage()
		page.Goto("https://hub.docker.com/")
	}

# LLM Client

After opening a page, we need to create a new LLM client. Currently, we support `anthropic` and `openai`. The `LlmClient` struct is available in `github.com/vertexcover-io/locatr/core`.

	import (
		"github.com/vertexcover-io/locatr"
		"os"
	)

	llmClient, err := locatr.NewLlmClient(
		os.Getenv("LLM_PROVIDER"), // Supported providers: "openai" | "anthropic"
		os.Getenv("LLM_MODEL_NAME"),
		os.Getenv("LLM_API_KEY"),
	)

# Options

Once we have an `llmClient`, we need to configure `BaseLocatrOptions`. This struct sets caching and configuration options.

	options := locatr.BaseLocatrOptions{UseCache: true, CachePath: ".locatr.cache"}

- `CachePath` has a default value of ".locatr.cache".

- `UseCache` is false by default. To enable caching, set `UseCache` to `true`.

# Playwright Locatr

Now, we can create a new `PlaywrightLocatr` instance by calling `NewPlaywrightLocatr` with the `page`, `llmClient`, and `options`.

	playWrightLocatr := locatr.NewPlaywrightLocatr(page, llmClient, options)

To locate an element, use the `GetLocatr` method. This method takes a descriptive string as input and returns a `Locator` object.

	searchBarLocator, err := playWrightLocatr.GetLocatr("Search Docker Hub input field")

The `GetLocatr` method returns either an error or a Playwright locator object. You can then interact with the located element through the returned locator.

	fmt.Println(searchBarLocator.InnerHTML())
	stringToSend := "Python"
	err = searchBarLocator.Fill(stringToSend)

# Caching

The cache is stored in json format. The schema is as follows:

	{
		"Page Full Url" : [
			{
				"locatr_name": "The description of the element you gave",
				"locatrs": [
					input#search",
				]
			}
		]
	}

To remove the cache, you should delete the file at the path specified in `BaseLocatrOptions`.

# Logging

Logging is enabled by default in locatr and it's set to `Info` log level. Pass the `LogConfig` value in the `BaseLocatrOptions` struct.

	options := locatr.BaseLocatrOptions{UseCache: true, LogConfig: locatr.LogConfig{Level: locatr.Debug}}

# Available Log Levels

The following log levels are available, in increasing order of priority:

- Debug: Logs all messages, info, warn, error.

- Info (Default): Logs informational messages, warnings, and errors.

- Warning: Logs warnings and errors only.

- Error: Logs only error messages.

# Locatr Results

Locatr provides a feature to get information about each locatr request made, using the GetLocatr function. Each result follows the schema outlined below.

Result Schema:

- LocatrDescription (string): Description of the locatr passed to the request.

- CacheHit (bool): Indicates if the result was retrieved from the cache (true) or freshly generated (false).

- Locatr (string): The locatr generated by the operation.

- InputTokens (int): Number of input tokens processed by the LLM call.

- OutputTokens (int): Number of tokens generated in the output by the LLM call.

- TotalTokens (int): Sum of input and output tokens.

- ChatCompletionTimeTaken (int): Time taken (in milliseconds) for the LLM to complete locatr generation.

Saving Results:

Results can be saved to a file specified by locatr.BaseLocatrOptions.ResultsFilePath. If no file path is specified, results are written to locatr.DEFAULT_LOCATR_RESULTS_PATH.

- To write results to a file, use the playwrightLocatr.WriteResultsToFile function.

Schema of the JSON file:

Each entry in the JSON file will follow this format:

	{
	  "locatr_description": "Example locatr description",
	  "cache_hit": true,
	  "locatr": "generated_locatr_string",
	  "input_tokens": 10,
	  "output_tokens": 5,
	  "total_tokens": 15,
	  "llm_locatr_generation_time_taken": 120
	}

- To retrieve results as a slice, use the playwrightLocatr.GetLocatrResults function
*/
package locatr
