name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  unit:
    strategy:
      matrix:
        python: ['3.12'] 
        os: [ubuntu-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install the latest version of uv (if required)
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Run Tests
        run: uv sync && pytest -s

